### ISSUE TITLE
Web portal once on WiFi

### ISSUE THREAD

**Issue by jaburges** [fireflyelectronix/wifidoorbell#12]
Feature request (as with the Sonoff devices running Tasmota firmware) there is a web portal allowing OTA firmware updates, MQTT server edits and WiFi edits without the need for manual intervention. Would a web portal have significant battery drain?

**Comment by fireflyelectronix** [comment]
The device needs to go into sleep mode in order to conserver battery power. This doesn't allow for a web portal to be always up.
