### ISSUE TITLE
Doesn't report doorbell alert

### ISSUE THREAD

**Issue by jaburges** [fireflyelectronix/wifidoorbell#14]
After a reflash, solving the WiFi issue (and the correct MQTT server format) i'm now seeing MQTT messages for the battery status - however the doorbell ring does not send an MQTT message. 

I'm using a video doorbell (not Ring) - but this should not change how the system works given the chime still "Ding Dongs" when pressed - so this device should be able to identify the button press?

**Comment by fireflyelectronix** [comment]
Hello, @jaburges the doorbell sensor works with ac voltage from traditional doorbells. Do you still use the ac doorbell with your video doorbell?

**Comment by jaburges** [comment]
yep - standard AC voltage. Replaced the old push button doorbell with the video doorbell.

Its working about 1 in every 30 times - so really not usable

**Comment by wonderslug** [comment]
Howdy all,

I think im seeing this as an issue as well.  I just installed the doorbell sensor using a Hikvision DS-KB6003-WIP video doorbell.  It providing an AC current to the doorbell to cause the ring to happen.  Its possible that the voltage is provided to trigger the wake up.  I do notice the bell sound is not a loud with the doorbell cam then with the normal button.  I have not checked the voltage provided yet.  What is the minimum AC Voltage needing to be sent in order to trigger and wake from deep sleep?

**Comment by fireflyelectronix** [comment]
Hi @wonderslug We have tested the doorbell sensor to trigger down to 8VAC. Is the Hikvision connected to both the doorbell sensor and the doorbell chime?

**Comment by wonderslug** [comment]
Howdy 

The HikVision is connected to the chime.  The chime is connected to to the sensor as in the second connection diagram on the docs.

I did get this working.  I noticed that there was a low voltage (1.2 AVC) going across the chime terminals even when the button wasn't pressed.   I was not getting a hum or odd chime but it was still there.  I added a high value resistor (came with the HikVision/Laview) to between the terminals of the chime and the sensor was able to detect the button press.

**Comment by jaburges** [comment]
@wonderslug how high of a value resistor? Have you had reliable results?

**Comment by Beertje135** [comment]
Hello, I'm having the same problem for a while nog. Only 1 in 30 presses is send to MQTT in Home Assistant. Did the resistor give any solution? and how is this done? 
Please some help. Are there any new Firmwares out? or is the last one from last year??
thanks in advance

**Comment by jaburges** [comment]
i removed this from my system - as couldnt get it to work.

Moved to a unifi G4 doorbell instead - closing this as not seen the vendor/dev respond since Jan 2020
